---
title: "updated chempop"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(here)
library(ggplot2)
library(plotly)
library(lme4)
library(sf)
library(leaflet)
library(shiny)
library(gganimate)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggmap)
library(osmdata)
```

```{r}
#read in the dataset
chempop <- read.csv(here("data", "Chempop", "updated chempop", "river_health_atlas_analysis_ready.csv"))

#colnames(chempop)

```

```{r}
chempop <- chempop %>%
  select(assemblage, sample_id, sample_date, sample_year, site_id, bio_site_id, site_label, reporting_area, sample_method, analysis_id, integration_unit, catchment, water_body, wfd_waterbody_id, reporting_area, easting, northing, longitude, latitude, taxon_richness, abundance_total, taxon_record_count, metric_count, metric_value_count, ept_taxon_richness, zinc_total_mean_6mo, copper_total_mean_6mo, cadmium_mean_6mo, chromium_mean_6mo, lead_mean_6mo, mercury_mean_6mo, nickel_mean_6mo, ph_mean_6mo, water_temperature_c_mean_6mo) %>% #select the columns that i want
  mutate(sample_date = as.Date(sample_date)) %>% #make sure date is stored as a date
  filter(sample_date >= as.Date("2000-01-01")) #filter for dates from 2000 onwards



chempop <- chempop %>%
  st_as_sf(
    coords = c("easting", "northing"), #change eastings and northings into a coordinate reference system
    crs = 27700
  ) %>%
  st_transform(4326) %>% #for each chemical, if the concentration is outside the first 95% of that chemical, then give it a value of NA. this is because I want to focus on the first 95% of each chemical, because the outlier values are really difficult to plot and deal with.
mutate(

    zinc_total_mean_6mo = if_else(
      zinc_total_mean_6mo >
        quantile(
          zinc_total_mean_6mo,
          0.95,
          na.rm = TRUE
        ),
      NA_real_,
      zinc_total_mean_6mo
    ),

    copper_total_mean_6mo = if_else(
      copper_total_mean_6mo >
        quantile(
          copper_total_mean_6mo,
          0.95,
          na.rm = TRUE
        ),
      NA_real_,
      copper_total_mean_6mo
    ),

    cadmium_mean_6mo = if_else(
      cadmium_mean_6mo >
        quantile(
          cadmium_mean_6mo,
          0.95,
          na.rm = TRUE
        ),
      NA_real_,
      cadmium_mean_6mo
    ),

    chromium_mean_6mo = if_else(
      chromium_mean_6mo >
        quantile(
          chromium_mean_6mo,
          0.95,
          na.rm = TRUE
        ),
      NA_real_,
      chromium_mean_6mo
    ),

    lead_mean_6mo = if_else(
      lead_mean_6mo >
        quantile(
          lead_mean_6mo,
          0.95,
          na.rm = TRUE
        ),
      NA_real_,
      lead_mean_6mo
    ),

    mercury_mean_6mo = if_else(
      mercury_mean_6mo >
        quantile(
          mercury_mean_6mo,
          0.95,
          na.rm = TRUE
        ),
      NA_real_,
      mercury_mean_6mo
    ),

    nickel_mean_6mo = if_else(
      nickel_mean_6mo >
        quantile(
          nickel_mean_6mo,
          0.95,
          na.rm = TRUE
        ),
      NA_real_,
      nickel_mean_6mo
    ),
    water_temperature_c_mean_6mo = if_else(
      water_temperature_c_mean_6mo >
        quantile(
          water_temperature_c_mean_6mo,
          0.95,
          na.rm = TRUE
        ),
      NA_real_,
      water_temperature_c_mean_6mo
    ),
    ph_mean_6mo = if_else(
      ph_mean_6mo >
        quantile(
          ph_mean_6mo,
          0.95,
          na.rm = TRUE
        ),
      NA_real_,
      ph_mean_6mo
    )

  )
  
```


```{r}
# Variables that I want to be able to select in the Rshiny app
variable_choices <- c(

  "Zinc" = "zinc_total_mean_6mo",
  "Copper" = "copper_total_mean_6mo",
  "Cadmium" = "cadmium_mean_6mo",
  "Chromium" = "chromium_mean_6mo",
  "Lead" = "lead_mean_6mo",
  "Mercury" = "mercury_mean_6mo",
  "Nickel" = "nickel_mean_6mo",
  "pH" = "ph_mean_6mo",
  "Water temperature" = "water_temperature_c_mean_6mo",
  "Sample date" = "sample_date",
  "Taxon richness" = "taxon_richness",
  "EPT taxon richness" = "ept_taxon_richness"

)
```


```{r}
#make the Rshiny app
ui <- fluidPage(

  titlePanel("Chempop dataset"),

  sidebarLayout(

    sidebarPanel( 

      selectInput(
        inputId = "x_variable",
        label = "Select x variable:",
        choices = variable_choices,
        selected = "zinc_total_mean_6mo"
      ),

      selectInput(
        inputId = "y_variable",
        label = "Select y variable:",
        choices = variable_choices,
        selected = "copper_total_mean_6mo"
      )

    ),

    mainPanel(

      plotOutput(
        "scatterplot",
        height = 700
      )

    )

  )

)

server <- function(input, output, session) {

  output$scatterplot <- renderPlot({

    ggplot(

      chempop,

      aes(
        x = .data[[input$x_variable]],
        y = .data[[input$y_variable]]
      )

    ) +

      geom_point(
        alpha = 0.6
      ) +

      geom_smooth(
        method = "lm",
        se = TRUE
      ) +

      labs(

        x = names(variable_choices)[
          variable_choices == input$x_variable
        ],

        y = names(variable_choices)[
          variable_choices == input$y_variable
        ],

        title = paste(

          names(variable_choices)[
            variable_choices == input$y_variable
          ],

          "vs",

          names(variable_choices)[
            variable_choices == input$x_variable
          ]

        )

      ) +

      theme_minimal() +


      theme(

        # Axis titles
        axis.title.x = element_text(
          size = 18,
          face = "bold"
        ),

        axis.title.y = element_text(
          size = 18,
          face = "bold"
        ),

        # Axis numbers/tick labels
        axis.text.x = element_text(
          size = 14
        ),

        axis.text.y = element_text(
          size = 14
        ),

        # Optional: make the title larger
        plot.title = element_text(
          size = 20,
          face = "bold"
        )

      )

  })

}

shinyApp(ui, server)
```



Making an animated Rshiny app to show mean annual concentration at each site over time

```{r}


chempop_filtered <- chempop %>% 
  #filter(
   # zinc_total_mean_6mo <= quantile(zinc_total_mean_6mo, 0.95, na.rm = TRUE),
    #copper_total_mean_6mo <= quantile(copper_total_mean_6mo, 0.95, na.rm = TRUE)) %>% #focus on the first 95% of data to make it easier to plot
  select(assemblage, sample_id, sample_date, sample_year, site_id, geometry, zinc_total_mean_6mo, copper_total_mean_6mo) %>%
  filter(
    !(is.na(zinc_total_mean_6mo) &
      is.na(copper_total_mean_6mo)))


#calculate the mean concentration for each site for each year
chempop_summaries <- chempop_filtered %>%
  group_by(sample_year, site_id) %>%
  summarise(
    mean_zinc = mean(zinc_total_mean_6mo, na.rm = TRUE),
    mean_copper = mean(copper_total_mean_6mo, na.rm = TRUE),
    .groups = "drop"
  )

#one site in 2023 is stored as MULTIPOINT instead of POINT and this causes problems later. this fixes it:
chempop_summaries <- chempop_summaries %>%
  st_cast("POINT")

```



 now I'm trying things with animations
 
 
```{r}
#defines the ranges to be used for the legend
zinc_range <- range(
  chempop_summaries$mean_zinc,
  na.rm = TRUE
)

copper_range <- range(
  chempop_summaries$mean_copper,
  na.rm = TRUE
)
```
 
 
 
```{r}
ui <- fluidPage(

  titlePanel("Mean Metal Concentrations"),

  sidebarLayout(
    sidebarPanel(

  sliderInput(
    inputId = "sample_year",
    label = "Select year:",
    min = min(chempop_summaries$sample_year, na.rm = TRUE),
    max = max(chempop_summaries$sample_year, na.rm = TRUE),
    value = min(chempop_summaries$sample_year, na.rm = TRUE),
    step = 1,
    sep = "",
    animate = animationOptions(
      interval = 1000,
      loop = TRUE
    )
  ),

  selectInput(
    inputId = "compound",
    label = "Select metal:",
    choices = c(
      "Zinc" = "mean_zinc",
      "Copper" = "mean_copper"
    ),
    selected = "mean_zinc"
  )

)
    ,

    mainPanel(

      leafletOutput(
        "metal_map",
        height = 700
      )

    )

  )

)

server <- function(input, output, session) {

  # Fixed concentration ranges across ALL years
  zinc_range <- range(
    chempop_summaries$mean_zinc,
    na.rm = TRUE
  )

  copper_range <- range(
    chempop_summaries$mean_copper,
    na.rm = TRUE
  )


  # Filter by selected year
  selected_year_data <- reactive({

    chempop_summaries %>%

      filter(
        sample_year == input$sample_year
      )

  })


  # Initialise map
  output$metal_map <- renderLeaflet({

    leaflet() %>%

      addProviderTiles(
        providers$CartoDB.Positron
      )

  })


  # Update map
observe({

  data <- selected_year_data()


  # Select concentration column
  concentration <- data[[input$compound]]


  # Remove NA and NaN values
  valid <- !is.na(concentration) & !is.nan(concentration)

  data <- data[valid, ]

  concentration <- concentration[valid]


  # Create a fixed colour palette
  pal <- if (input$compound == "mean_zinc") {

    colorNumeric(
      palette = "YlOrRd",
      domain = zinc_range,
      na.color = "transparent"
    )

  } else {

    colorNumeric(
      palette = "YlOrRd",
      domain = copper_range,
      na.color = "transparent"
    )

  }


  # Get readable metal name
  metal_name <- ifelse(

    input$compound == "mean_zinc",

    "Zinc",

    "Copper"

  )


  leafletProxy(

    "metal_map",

    data = data

  ) %>%

    clearMarkers() %>%

    clearControls() %>%

    addCircleMarkers(

      radius = 6,

      fillColor = pal(concentration),

      fillOpacity = 0.8,

      color = "black",

      weight = 1,

      popup = paste0(

        "<b>Site:</b> ",
        data$site_id,

        "<br><b>Year:</b> ",
        data$sample_year,

        "<br><b>Mean ",
        tolower(metal_name),
        ":</b> ",

        round(concentration, 4),

        " µg/L"

      )

    ) %>%

    addLegend(

      pal = pal,

      values = if (input$compound == "mean_zinc") {

        zinc_range

      } else {

        copper_range

      },

      title = paste(

        "Mean",

        metal_name,

        "(µg/L)"

      ),

      position = "bottomright"

    )

})

}

shinyApp(ui, server)
```
 
 
 
 
 
 
 
 This creates a gif that you can save
 the Rshiny app is probably more useful but this can be embedded in powerpoints, etc, and i think it's cool...
 
 
```{r}
#read in the hydrometric areas dataset
hydrometric_areas <- st_read(
  here("data", "hydrometric_areas_with_coastline", "data", "hyd_areas.shp")
)

hydrometric_areas <- hydrometric_areas %>%
  st_transform(st_crs(chempop_summaries))
```

```{r}
p <- ggplot() +

  # Hydrometric areas
  geom_sf(
    data = hydrometric_areas,
    fill = "grey80",
    colour = "white",
    linewidth = 0.2
  ) +

  # Zinc sampling sites
  geom_sf(
    data = chempop_summaries,
    aes(
      colour = mean_zinc
    ),
    size = 2,
    alpha = 0.8
  ) +

  scale_colour_distiller(
    palette = "YlOrRd",
    direction = 1,
    name = "Mean zinc (µg/L)",
    limits = range(
      chempop_summaries$mean_zinc,
      na.rm = TRUE
    )
  ) +

  labs(
    title = "Mean zinc concentrations: {frame_time}"
  ) +

  theme_minimal() +

  transition_time(sample_year) +

  ease_aes("linear")

animation <- animate(
  p,
  fps = 1,
  duration = 20,
  width = 1000,
  height = 700,
  renderer = gifski_renderer()
)

animation



anim_save(
  here("figures", "zinc_animation.gif"),
  animation = animation
)
```










