---
title: "plotting catchments"
output: html_document
---

```{r}
library(shiny)
library(bslib)
library(dplyr)
library(ggplot2)
library(ggExtra)
library(sf)
library(leaflet)
library(openxlsx)
library(here)
library(terra)
library(viridisLite)
```

```{r}
#read in the hydrometric areas dataset
hydrometric_areas <- st_read(
  here("data", "hydrometric_areas_with_coastline", "data", "hyd_areas.shp")
)
#this plots the hydrometric areas
#plot(st_geometry(hydrometric_areas))

#transform the longitude/latitude coodinates into a coordinate reference system
hydrometric_areas_rain <- st_transform(hydrometric_areas, crs(rainfall_2025))

```

```{r}
#read in all the rainfall data from different years
rainfall_2025 <- rast(
  here("data", "monthly_rainfall_5km", "rainfall_2025.nc"))

rainfall_2024 <- rast(
  here("data", "monthly_rainfall_5km", "rainfall_2024.nc"))

rainfall_2023 <- rast(
  here("data", "monthly_rainfall_5km", "rainfall_2023.nc"))

rainfall_2022 <- rast(
  here("data", "monthly_rainfall_5km", "rainfall_2022.nc"))

rainfall_2021 <- rast(
  here("data", "monthly_rainfall_5km", "rainfall_2021.nc"))

rainfall_2020 <- rast(
  here("data", "monthly_rainfall_5km", "rainfall_2020.nc"))



#write a function to clean the rainfall data, so that the layers are assigned months
clean_rainfall <- function(rainfall) {

  # Give layers month names
  names(rainfall) <- month.abb[seq_len(nlyr(rainfall))]

  rainfall}

#apply this function to all the datasets
rainfall_2025 <- clean_rainfall(rainfall_2025)
rainfall_2024 <- clean_rainfall(rainfall_2024)
rainfall_2023 <- clean_rainfall(rainfall_2023)
rainfall_2022 <- clean_rainfall(rainfall_2022)
rainfall_2021 <- clean_rainfall(rainfall_2021)
rainfall_2020 <- clean_rainfall(rainfall_2020)

#plot the data
#plot(rainfall_2025)



```

```{r}
# fixed colour scale across all months
#set breaks, from 0 - 700, by increments size 100
brks <- c(seq(0, 700, by = 100), Inf)

#store all the rainfall datasets in a list
rainfall <- list(
  "2020" = rainfall_2020,
  "2021" = rainfall_2021,
  "2022" = rainfall_2022,
  "2023" = rainfall_2023,
  "2024" = rainfall_2024,
  "2025" = rainfall_2025
)

```


```{r}
#now make the rshiny application
ui <- fluidPage(
  titlePanel("Monthly Rainfall"),

  sidebarLayout(
    sidebarPanel(

      selectInput(
        "year",
        "Choose a year",
        choices = names(rainfall),
        selected = "2025"
      ),

      selectInput(
        "month",
        "Choose a month",
        choices = names(rainfall[[1]]),
        selected = names(rainfall[[1]])[1]
      )

    ),

    mainPanel(
      plotOutput("rain_map", height = "500px")
    )
  )
)

server <- function(input, output, session) {

  selected_rain <- reactive({
    req(input$year, input$month)

    rainfall[[input$year]][[input$month]]
  })

  output$rain_map <- renderPlot({

    r <- selected_rain()

    plot(
      r,
      main = paste("Rainfall:", input$month, input$year),
      col = viridis(50),
      breaks = brks
    )

    plot(
      st_geometry(hydrometric_areas_rain),
      add = TRUE,
      border = "black",
      lwd = 0.5
    )
  })
}

shinyApp(ui, server)
```










This is a version using leaflet map but it is kind of clunky and ugly so I'm not sure its very good. Probably better to stick to using the static map above.
```{r}
# transform hydrometric areas to WGS84 for leaflet
hydrometric_areas_ll <- st_transform(hydrometric_areas, 4326)

# fixed colour scale across all months
global_range <- range(values(rainfall), na.rm = TRUE)
brks <- seq(global_range[1], global_range[2], length.out = 51)
pal <- colorNumeric(palette = viridis(50), domain = global_range)

ui <- fluidPage(
  titlePanel("Rainfall in 2025"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput(
        inputId = "month",
        label = "Choose a month",
        choices = names(rainfall),
        selected = names(rainfall)[1]
      )
    ),
    
    mainPanel(
      leafletOutput("rain_map", height = "700px")
    )
  )
)

server <- function(input, output, session) {
  
  selected_rain <- reactive({
    req(input$month)
    rainfall[[input$month]]
  })
  
  output$rain_map <- renderLeaflet({
    r <- selected_rain()
    
    leaflet() |>
      addProviderTiles(providers$CartoDB.Positron) |>
      addRasterImage(
        r,
        colors = pal,
        opacity = 0.8,
        project = TRUE
      ) |>
      addPolygons(
        data = hydrometric_areas_ll,
        fill = FALSE,
        color = "black",
        weight = 0.5
      ) |>
      addLegend(
        pal = pal,
        values = global_range,
        title = paste("Rainfall -", input$month),
        opacity = 1
      )
  })
}

shinyApp(ui, server)
```



