---
title: "imidacloprid choropleth"
output: html_document
---

```{r}
library(biscale)
library(sf)
library(cowplot)
library(leaflet)
```

```{r}
#read in the dataset of imidacloprid

#try reading in all of the datasets at once, as a excel spreadsheet
#this reads in all of the sheets at once!
file_in <- here("data", "Pharmaceuticals infomation_V3.xlsx")

# Get the name of the sheets.
f_sheets <- getSheetNames(file_in)
 
# Read in the ibuprofen data
imidacloprid <- read.xlsx(file_in, sheet = "Imidacloprid_LCMS")

#store year as an integer
imidacloprid$year <- as.integer(imidacloprid$year)

#store datetime as datetime
imidacloprid$Sample_datetime <- ymd_hms(imidacloprid$Sample_datetime)

```

```{r}
imidacloprid_sf <- imidacloprid %>%
  select(Concentration, year, Longitude, Latitude, Sample_Site_ID, Sample_datetime) %>% #select the columns that I want
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) #%>% #converts coordinate column into a geometry column
  #mutate(log_Concentration = log(Concentration))

#because I am plotting by sample site ID, i need to remove sites where the site ID has been redacted. 
#otherwise it gets really confusing with the same sample site ID have multiple coordinates
imidacloprid_sf <- imidacloprid_sf %>%
  filter(Sample_Site_ID != "REDACTED")
```

```{r}
#calculate the median number of samples per year at each site, and also the number of years that each site has been sampled.
site_summaries <- imidacloprid_sf %>%
  group_by(Sample_Site_ID, year) %>%
  summarise(
    annual_samples = n(),
    .groups = "drop"
  ) %>%
  group_by(Sample_Site_ID) %>%
  summarise(
    median_annual_samples = median(annual_samples),
    years_sampled = n_distinct(year),
    .groups = "drop"
  )

```



```{r}
# create biscale classes, adds this column onto the site_summaries dataset
#site_summaries <- bi_class(site_summaries, x = median_annual_samples, y = years_sampled, style = "equal", dim = 2)


#manually assign biscale classes
site_summaries <- site_summaries %>%
  mutate(
    x_class = case_when(
      median_annual_samples == 1 ~ 1,
      median_annual_samples > 1 & median_annual_samples < 5 ~ 2,
      median_annual_samples >= 5 ~ 3
    ),
    y_class = case_when(
      years_sampled == 1 ~ 1,
      years_sampled >= 2 & years_sampled <= 3 ~ 2,
      years_sampled >= 4 ~ 3
    ),
    bi_class = paste(x_class, y_class, sep = "-")
  )
```




```{r}

cols <- c(
  "1-1" = "#e8e8e8",
  "1-2" = "#ace4e4",
  "1-3" = "#5ac8c8",
  "2-1" = "#dfb0d6",
  "2-2" = "#a5add3",
  "2-3" = "#5698b9",
  "3-1" = "#be64ac",
  "3-2" = "#8c62aa",
  "3-3" = "#3b4994"
)

site_summaries$colour <- cols[as.character(site_summaries$bi_class)]

leaflet(site_summaries) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addCircleMarkers(
    radius = 5,
    stroke = TRUE,
    color = "black",
    weight = 1,
    fill = TRUE,
    fillColor = ~colour,
    fillOpacity = 0.9,
    popup = ~paste(
      "<b>Median annual samples:</b>", median_annual_samples, "<br>",
      "<b>Years sampled:</b>", years_sampled, "<br>",
      "<b>Class:</b>", bi_class
    )
  )


pal <- colorFactor(
  palette = cols,
  domain = names(cols)
)

leaflet(site_summaries) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addCircleMarkers(
    radius = 5,
    stroke = TRUE,
    color = "black",
    weight = 1,
    fill = TRUE,
    fillColor = ~pal(bi_class),
    fillOpacity = 0.9
  )



```



```{r}
pal <- colorFactor(
  palette = c(
    "1-1" = "#e8e8e8",
    "1-2" = "#64acbe",
    "2-1" = "#c85a5a",
    "2-2" = "#574249"
  ),
  domain = site_summaries$bi_class
)

leaflet(site_summaries) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addCircleMarkers(
    radius = 5,
    stroke = TRUE,
    color = "black",
    weight = 1,
    fill = TRUE,
    fillColor = ~pal(bi_class),
    fillOpacity = 0.9
  )
```

