---
title: "Specific site"
output: html_document
---

```{r}
library(readxl)
library(dplyr)
library(purrr)
library(here)
library(ggplot2)
library(hrbrthemes)
library(RColorBrewer)
library(lubridate)
library(viridis)
library(scales)
library(ggridges)
```

```{r}
#read in the excel spreadsheet
file <- here("data", "Pharmaceuticals infomation_V3.xlsx")

#to find out which sheets have data on the site WAV120
excel_sheets(file) %>%
  keep(~{
    dat <- read_excel(file, sheet = .x)
    "WAV120" %in% dat$Sample_Site_ID
  })

#store these sheets that have data on WAV120 in an object called site_sheets
site_sheets <- excel_sheets(file) %>%
  keep(~{
    dat <- read_excel(file, sheet = .x)
    "WAV120" %in% dat$Sample_Site_ID
  })
```


```{r}
#get all data from a specific site

#specify which columns i want
cols <- c(
  "Sample_Site_ID",
  "Sample_datetime",
  "Compound_Name",
  "Concentration",
  "unit",
  "year"
)


#extract all the data for those columns
wav120_data <- map_dfr(site_sheets, ~{

  read_excel(file, sheet = .x) %>%
    select(any_of(cols)) %>%
    filter(Sample_Site_ID == "WAV120") %>%
    mutate(
      Sample_datetime = as.POSIXct(Sample_datetime), #ensure that datetime is stored as datetime
      sheet = .x
    )

})

#get rid of this extreme outlier value, I don't think this is right..
#i have checked the raw data and lots of sites appear to have 9 ug/l of clarithromycin at around the same time, so maybe
#there is some kind of error in the measurements?
#i need to ask about this...
#wav120_data <- wav120_data %>%
  #filter(Concentration != 9)
```

```{r}
wav120_data %>%
  distinct(Compound_Name)
#there are 11 distinct compounds in this dataset

wav120_data %>%
  distinct(year)
#14 distinct years of sampling - from 2010 to 2024
```

```{r}
#calculate the mean concentration of each chemical in each year
wav120_yearly_means <- wav120_data %>%
  mutate(Year = year(Sample_datetime)) %>%
  group_by(Year, Compound_Name) %>%
  summarise(
    mean_concentration = mean(Concentration, na.rm = TRUE),
    n_samples = n(),
    .groups = "drop"
  )

#now try with median values instead
#wav120_yearly_medians <- wav120_data %>%
#  mutate(Year = year(Sample_datetime)) %>%
 # group_by(Year, Compound_Name) %>%
 # summarise(
 #   median_concentration = median(Concentration, na.rm = TRUE),
 #   n_samples = n(),
 #   .groups = "drop"
 # )
```


```{r}
#plot a heatmap using ggplot2
ggplot(wav120_yearly_means, aes(Year, Compound_Name, fill= mean_concentration)) + 
  geom_tile() +
  scale_fill_distiller(palette = "YlGnBu") +
  theme_bw()

#changes the colour palette
ggplot(wav120_yearly_means,
       aes(Year, Compound_Name, fill = mean_concentration)) +
  geom_tile() +
  scale_fill_viridis_c(option = "D") +
  theme_bw()

#try capping the colour scale - anything above 0.1 is shown in the maximum colour
ggplot(
  wav120_yearly_means,
  aes(Year, Compound_Name, fill = mean_concentration)
) +
  geom_tile() +
  scale_fill_viridis_c(
    limits = c(0, 0.1),
    oob = scales::squish,
    breaks = c(0, 0.025, 0.05, 0.075, 0.1),
    labels = c("0", "0.025", "0.05", "0.075", "\u2265 0.1")
  ) +
  labs(
    y = NULL,
    fill = expression(Concentration~"("*mu*"g L"^{-1}*")")
  ) +
  theme_bw()

#another option is to z-score each chemical, so that it is given a mean of 0 and a standard deviation of 1
wav120_scaled <- wav120_yearly_means %>%
  group_by(Compound_Name) %>%
  mutate(
    scaled_conc = scale(mean_concentration)[,1]
  ) %>%
  ungroup()




#normalise the data
#when there is only one datapoint, you can't calculate a z-score
wav120_scaled_complete <- wav120_scaled %>%
  complete(
    Year = 2010:2024,   
    Compound_Name,
    fill = list(scaled_conc = NA)
  )



#plot a heatmap of these z-scores
ggplot(wav120_scaled_complete,
       aes(Year, Compound_Name, fill = scaled_conc)) +
  geom_tile() +
  scale_fill_gradient2(
    low = "green",
    mid = "white",
    high = "blue",
    midpoint = 0,
    na.value = "grey"
  ) +
  labs(
    y = NULL,
    fill = "Z-score"
  ) +
  theme_bw() #+ 
  #theme(
    #panel.background = element_rect(fill = "black")
  #)


```
```{r}
#remove clarithromycin because that one high measurement is making the data really difficult to visualise
#wav120_yearly_means <- wav120_yearly_means %>%
  #filter(Compound_Name != "Clarithromycin")%>%
  #filter(Compound_Name != "Ibuprofen")

#make a bar plot of the mean concentration of each chemical over each year
barplot <- ggplot(wav120_yearly_means, aes(x=Compound_Name, y=mean_concentration)) + 
  geom_bar(stat = "identity") +
  facet_wrap(~ Year) +
  coord_flip()

barplot


ggsave(
  here("figures", "barplot.png"),
  plot = barplot,
  width = 20,
  height = 10,
  dpi = 300
)



ggplot(wav120_yearly_means, aes(x=Compound_Name, y=mean_concentration)) + 
  geom_bar(stat = "identity") +
  facet_wrap(~ Year) + 
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))


```


```{r}
#timeseries plot with ggplotly and Rshiny
ui <- fluidPage(

  titlePanel("Site WAV120"),

  sidebarLayout(

    sidebarPanel(

      checkboxGroupInput(
        inputId = "compound",
        label = "Select compounds:",
        choices = sort(unique(wav120_data$Compound_Name)),
        selected = unique(wav120_data$Compound_Name)[1:3]
      )

    ),

    mainPanel(
      plotlyOutput("timeseries", height = "700px")
    )

  )

)

server <- function(input, output, session) {

  filtered_data <- reactive({

    wav120_data %>%
      filter(Compound_Name %in% input$compound)

  })

  output$timeseries <- renderPlotly({

    p <- ggplot(
      filtered_data(),
      aes(
        x = Sample_datetime,
        y = Concentration,
        colour = Compound_Name,
        group = Compound_Name,
        text = paste0(
          "<b>", Compound_Name, "</b>",
          "<br>Date: ", Sample_datetime,
          "<br>Concentration: ", round(Concentration, 3), " µg/L"
        )
      )
    ) +
      geom_line() +
      geom_point() +
      scale_colour_viridis_d(option = "D") +
      labs(
    x = "Date",
    y = "Concentration (µg/L)",
    colour = "Compound") +
      theme_bw()

    ggplotly(p, tooltip = "text")

  })

}

shinyApp(ui, server)
```

```{r}
#ridgeline plot
# basic example
ggplot(wav120_data, aes(x = Concentration, y = Compound_Name, fill = Compound_Name)) +
  geom_density_ridges() +
  theme_ridges() + 
  coord_cartesian(xlim = c(0, 0.15)) +
  theme(legend.position = "none")
```

