---
title: "Specific site"
output: html_document
---

```{r}
library(readxl)
library(dplyr)
library(purrr)
library(here)
library(ggplot2)
library(hrbrthemes)
library(RColorBrewer)
library(lubridate)
library(viridis)
library(scales)
library(ggridges)
```

```{r}
#read in the excel spreadsheet
file <- here("data", "Pharmaceuticals infomation_V3.xlsx")

#to find out which sheets have data on the site WAV120
#excel_sheets(file) %>%
 # keep(~{
 #   dat <- read_excel(file, sheet = .x)
 #   "WAV120" %in% dat$Sample_Site_ID
 # })

#store these sheets that have data on WAV120 in an object called site_sheets
#site_sheets <- excel_sheets(file) %>%
 # keep(~{
 #   dat <- read_excel(file, sheet = .x)
 #   "WAV120" %in% dat$Sample_Site_ID
 # })

#this code doesn't assume that every sheet has the column Sample_Site_ID
site_sheets <- excel_sheets(file) %>%
  keep(~{
    dat <- read_excel(file, sheet = .x)

    if (!"Sample_Site_ID" %in% names(dat)) {
      return(FALSE)
    }

    "WAV120" %in% dat$Sample_Site_ID
  })
```


```{r}
#get all data from a specific site

#specify which columns i want
cols <- c(
  "Sample_Site_ID",
  "Sample_datetime",
  "Compound_Name",
  "Concentration",
  "unit",
  "year"
)


#extract all the data for those columns
wav120_data <- map_dfr(site_sheets, ~{

  read_excel(file, sheet = .x) %>%
    select(any_of(cols)) %>%
    filter(Sample_Site_ID == "WAV120") %>%
    mutate(
      Sample_datetime = as.POSIXct(Sample_datetime), #ensure that datetime is stored as datetime
      sheet = .x
    )

})

#get rid of this extreme outlier value, I don't think this is right..
#i have checked the raw data and lots of sites appear to have 9 ug/l of clarithromycin at around the same time, so maybe
#there is some kind of error in the measurements?
#i need to ask about this...
#wav120_data <- wav120_data %>%
  #filter(Concentration != 9)
```



```{r}
#calculate the mean concentration of each chemical in each year
wav120_yearly_means <- wav120_data %>%
  mutate(Year = year(Sample_datetime)) %>%
  group_by(Year, Compound_Name) %>%
  summarise(
    mean_concentration = mean(Concentration, na.rm = TRUE),
    n_samples = n(),
    .groups = "drop"
  )

#now try with median values instead
#wav120_yearly_medians <- wav120_data %>%
#  mutate(Year = year(Sample_datetime)) %>%
 # group_by(Year, Compound_Name) %>%
 # summarise(
 #   median_concentration = median(Concentration, na.rm = TRUE),
 #   n_samples = n(),
 #   .groups = "drop"
 # )
```


```{r}
#plot a heatmap using ggplot2


source(here("scripts", "mytheme.R"))

#try capping the colour scale - anything above 0.1 is shown in the maximum colour
heatmap1 <- ggplot(
  wav120_yearly_means,
  aes(Year, Compound_Name, fill = mean_concentration)
) +
  geom_tile() +
  scale_fill_viridis_c(
    limits = c(0, 0.1),
    oob = scales::squish,
    breaks = c(0, 0.025, 0.05, 0.075, 0.1),
    labels = c("0", "0.025", "0.05", "0.075", "\u2265 0.1")
  ) +
  labs(
    y = NULL,
    fill = expression(Concentration~"("*mu*"g L"^{-1}*")")
  ) +
  my_theme() +
  theme(
    axis.title.x = element_text(size = 20, face = "bold"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.text = element_text( size = 20),
    legend.title = element_text(size = 20, face = "bold"),
    legend.text = element_text(size = 18))

heatmap1

ggsave(
  here("figures", "heatmap1.png"),
  plot = heatmap1,
  width = 5,
  height = 3,
  dpi = 300,
    bg = "#F4F5F1"
)
```

```{r}
#another option is to z-score each chemical, so that it is given a mean of 0 and a standard deviation of 1
#normalise the data
#when there is only one datapoint, you can't calculate a z-score
wav120_scaled <- wav120_yearly_means %>%
  group_by(Compound_Name) %>%
  mutate(
    scaled_conc = scale(mean_concentration)[,1]
  ) %>%
  ungroup()


#complete the dataset so that I can plot NA values in grey
wav120_scaled_complete <- wav120_scaled %>%
  tidyr::complete(
    Year = 2010:2024,   
    Compound_Name,
    fill = list(scaled_conc = NA)
  )



#plot a heatmap of these z-scores
heatmap2 <- ggplot(wav120_scaled_complete,
       aes(Year, Compound_Name, fill = scaled_conc)) +
  geom_tile() +
  scale_fill_gradient2(
    low = "green",
    mid = "white",
    high = "blue",
    midpoint = 0,
    na.value = "grey"
  ) +
  labs(
    y = NULL,
    fill = "Z-score"
  ) +
  my_theme() +
  theme(
    axis.title.x = element_text(size = 20, face = "bold"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.text = element_text( size = 20),
    legend.title = element_text(size = 20, face = "bold"),
    legend.text = element_text(size = 18))

heatmap2

ggsave(
  here("figures", "heatmap2.png"),
  plot = heatmap2,
  width = 5,
  height = 3,
  dpi = 300,
    bg = "#F4F5F1"
)
```

```{r}
#read in the PNEC thresholds
thresholds <- read.csv(here("data", "thresholds(Sheet1).csv"))

#make the substance column have capital letters
thresholds$substance <- tools::toTitleCase(thresholds$substance)

#join the PNEC values onto the dataset
wav120_yearly_means <- wav120_yearly_means %>%
  left_join(
    thresholds,
    by = c("Compound_Name" = "substance")) %>%
  select(Year, Compound_Name, mean_concentration, n_samples, PNEC) %>% #complete all missing values so they are plotted as NAs
  tidyr::complete(
    Year = 2010:2024,   
    Compound_Name,
    fill = list(scaled_conc = NA)
  )

#now calculate the percentage above or below the threshold
#calculate the percentage difference of each observation relative to the PNEC
wav120_yearly_means <- wav120_yearly_means %>%
  mutate(
    pct_difference = ((mean_concentration - PNEC) / PNEC) * 100
  )


```



```{r}
#now plot as a heatmap
heatmap3 <- ggplot(wav120_yearly_means,
       aes(Year, Compound_Name, fill = pct_difference)) +
  geom_tile() +
  scale_fill_gradient2(
    low = "green",
    mid = "white",
    high = "blue",
    midpoint = 0,
    limits = c(-200, 200),
  oob = scales::squish,
  breaks = c(-200, -100, 0, 100, 200),
    labels = c("\u2264 -200", "-100", "0", "100", "\u2265 200"),
    na.value = "grey"
  ) +
  labs(
    y = NULL,
    fill = "Difference from PNEC (%)"
  ) +
  my_theme() +
  theme(
    axis.title.x = element_text(size = 20, face = "bold"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.text = element_text( size = 20),
    legend.title = element_text(size = 20, face = "bold"),
    legend.text = element_text(size = 18))

heatmap3

ggsave(
  here("figures", "heatmap3.png"),
  plot = heatmap3,
  width = 5,
  height = 3,
  dpi = 300,
    bg = "#F4F5F1"
)
```








