---
title: "timeseries"
output: html_document
---

```{r}
library(readxl)
library(dplyr)
library(purrr)
library(here)
library(ggplot2)
library(hrbrthemes)
library(RColorBrewer)
library(lubridate)
library(viridis)
library(scales)
library(ggridges)

library(tidyverse)
library(janitor)
library(showtext)
library(MetBrewer)
library(scico)
library(ggtext)
library(patchwork)
library(gghighlight)
library(shiny)
library(plotly)
```

```{r}
#read in the excel spreadsheet
file <- here("data", "Pharmaceuticals infomation_V3.xlsx")

#this code doesn't assume that every sheet has the column Sample_Site_ID
site_sheets <- excel_sheets(file) %>%
  keep(~{
    dat <- read_excel(file, sheet = .x)

    if (!"Sample_Site_ID" %in% names(dat)) {
      return(FALSE)
    }

    "WAV120" %in% dat$Sample_Site_ID
  })
```


```{r}
#get all data from a specific site

#specify which columns i want
cols <- c(
  "Sample_Site_ID",
  "Sample_datetime",
  "Compound_Name",
  "Concentration",
  "unit",
  "year"
)


#extract all the data for those columns
wav120_data <- map_dfr(site_sheets, ~{

  read_excel(file, sheet = .x) %>%
    select(any_of(cols)) %>%
    filter(Sample_Site_ID == "WAV120") %>%
    mutate(
      Sample_datetime = as.POSIXct(Sample_datetime), #ensure that datetime is stored as datetime
      sheet = .x
    )

})

#remove all rows where concentration i greater than or equal to 1, becuase this makes the data really hard to plot
wav120_data <- wav120_data %>%
  filter(Concentration < 1)
```


```{r}
#timeseries plot with ggplotly and Rshiny
ui <- fluidPage(

  titlePanel("Site WAV120"),

  sidebarLayout(

    sidebarPanel(

      checkboxGroupInput( #checkboxes to pick which chemicals to plot
        inputId = "compound",
        label = "Select compounds:",
        choices = sort(unique(wav120_data$Compound_Name)),
        selected = unique(wav120_data$Compound_Name)[1:3]
      )

    ),

    mainPanel(
      plotlyOutput("timeseries", height = "500px")
    )

  )

)

server <- function(input, output, session) {

  filtered_data <- reactive({

    wav120_data %>%
      filter(Compound_Name %in% input$compound)

  })

  output$timeseries <- renderPlotly({

    p <- ggplot(
      filtered_data(),
      aes(
        x = Sample_datetime,
        y = Concentration,
        colour = Compound_Name,
        group = Compound_Name,
        text = paste0( #displays the compound name, date and concentration when you hover over a point
          "<b>", Compound_Name, "</b>",
          "<br>Date: ", Sample_datetime,
          "<br>Concentration: ", round(Concentration, 3), " µg/L"
        )
      )
    ) +
      geom_line() +
      geom_point() +
      scale_colour_viridis_d(option = "D") +
      labs(
    x = "Date",
    y = "Concentration (µg/L)",
    colour = "Compound") +
      theme_bw()

    ggplotly(p, tooltip = "text")

  })

}

shinyApp(ui, server)
```
```{r}
#now try making a static plot of concentration over time, with a small graph for each chemical
#random aesthetic things
font <- "Gudea"
font_add_google(family=font, font, db_cache = TRUE)
fa_path <- systemfonts::font_info(family = "Font Awesome 6 Brands")[["path"]]
font_add(family = "fa-brands", regular = fa_path)
theme_set(theme_minimal(base_family = font, base_size = 10))
bg <- "#F4F5F1"
txt_col <- "black"
showtext_auto(enable = TRUE)




```

```{r}
#make the plot in ggplot2 
p1 <- wav120_data %>% 
  ggplot() +
  geom_point(data=wav120_data %>% 
               group_by(Compound_Name) %>% 
               slice_max(Sample_datetime),
             aes(x=Sample_datetime, y=Concentration, color=Compound_Name),shape=16) +
  geom_line(aes(x=Sample_datetime, y=Concentration, color=Compound_Name)) +
  gghighlight(use_direct_label = FALSE,
              unhighlighted_params = list(colour = alpha("grey85", 1))) +
  scale_color_met_d(name="Redon") +
  scale_x_datetime(date_labels = "%Y") +
  facet_wrap(~ Compound_Name) +
  facet_wrap(~  factor(Compound_Name, levels=c('Carbamazepine','Clarithromycin','Diazinon (Dimpylate)','Erythromycin', 'Fipronil','Fipronil amide', 'Fipronil sulfide', 'Fipronil sulfon (M & B 46136)', 'Ibuprofen','Imidacloprid', 'Ketoprofen'))) + 
  labs(
     #title = "Chemical pollution at site WAV120",
    x = "Year",
    y = "Concentration (μg/L)"
  ) +
  coord_cartesian(clip = "off") +
  theme(
    axis.title.x = element_text(size = 20, face = "bold"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.text = element_text(color = txt_col, size = 20),
    strip.text.x = element_text(size = 20, face = "bold"),
    plot.title = element_markdown(hjust=.5,size=20, color=txt_col,lineheight=.8, face="bold", margin=margin(20,0,30,0)),
    plot.subtitle = element_markdown(hjust=.5,size=18, color=txt_col,lineheight = 1, margin=margin(10,0,30,0)),
    plot.caption = element_markdown(hjust=.5, margin=margin(60,0,0,0), size=10, color=txt_col, lineheight = 1.2),
    plot.caption.position = "plot",
    plot.background = element_rect(color=bg, fill=bg),
    plot.margin = margin(10,10,10,10),
    legend.position = "none",
    legend.title = element_text(face="bold")
  )

p1

#save the plot in the figures folder
ggsave(
  here("figures", "timeseries at specific site.png"),
  plot = p1,
  width = 6,
  height = 3,
  dpi = 300,
    bg = "#F4F5F1"
)
```



