---
title: "imidacloprid choropleth"
output: html_document
---

```{r}
library(biscale)
library(sf)
library(cowplot)
library(leaflet)
library(here)
library(openxlsx)
library(lubridate)
library(dplyr)
library(sf)
library(leaflet)
library(htmltools)
library(ggplot2)
```

```{r}
#read in the dataset of imidacloprid

#try reading in all of the datasets at once, as a excel spreadsheet
#this reads in all of the sheets at once!
file_in <- here("data", "Pharmaceuticals infomation_V3.xlsx")

# Get the name of the sheets.
f_sheets <- getSheetNames(file_in)
 
# Read in the ibuprofen data
imidacloprid <- read.xlsx(file_in, sheet = "Imidacloprid_LCMS")

#store year as an integer
imidacloprid$year <- as.integer(imidacloprid$year)

#store datetime as datetime
imidacloprid$Sample_datetime <- ymd_hms(imidacloprid$Sample_datetime)

```

```{r}
imidacloprid_sf <- imidacloprid %>%
  select(Concentration, year, Longitude, Latitude, Sample_Site_ID, Sample_datetime) %>% #select the columns that I want
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) #%>% #converts coordinate column into a geometry column
  #mutate(log_Concentration = log(Concentration))

#because I am plotting by sample site ID, i need to remove sites where the site ID has been redacted. 
#otherwise it gets really confusing with the same sample site ID have multiple coordinates
imidacloprid_sf <- imidacloprid_sf %>%
  filter(Sample_Site_ID != "REDACTED")
```

```{r}
#calculate the median number of samples per year at each site, and also the number of years that each site has been sampled.
site_summaries <- imidacloprid_sf %>%
  group_by(Sample_Site_ID, year) %>%
  summarise(
    annual_samples = n(),
    .groups = "drop"
  ) %>%
  group_by(Sample_Site_ID) %>%
  summarise(
    median_annual_samples = median(annual_samples),
    years_sampled = n_distinct(year),
    .groups = "drop"
  )

```



```{r}
# create biscale classes, adds this column onto the site_summaries dataset
#site_summaries <- bi_class(site_summaries, x = median_annual_samples, y = years_sampled, style = "equal", dim = 2)


#manually assign biscale classes
site_summaries <- site_summaries %>%
  mutate(
    x_class = case_when(
      median_annual_samples == 1 ~ 1,
      median_annual_samples > 1 & median_annual_samples < 5 ~ 2,
      median_annual_samples >= 5 ~ 3
    ),
    y_class = case_when(
      years_sampled == 1 ~ 1,
      years_sampled >= 2 & years_sampled <= 3 ~ 2,
      years_sampled >= 4 ~ 3
    ),
    bi_class = paste(x_class, y_class, sep = "-")
  )
```


```{r}

cols <- c(
  "1-1" = "#e8e8e8",
  "1-2" = "#ace4e4",
  "1-3" = "#5ac8c8",
  "2-1" = "#dfb0d6",
  "2-2" = "#a5add3",
  "2-3" = "#5698b9",
  "3-1" = "#be64ac",
  "3-2" = "#8c62aa",
  "3-3" = "#3b4994"
)

site_summaries$colour <- cols[as.character(site_summaries$bi_class)]


pal <- colorFactor(
  palette = cols,
  domain = names(cols)
)

leaflet(site_summaries) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addCircleMarkers(
    radius = 5,
    stroke = TRUE,
    color = "black",
    weight = 1,
    fill = TRUE,
    fillColor = ~pal(bi_class),
    fillOpacity = 0.9
  )



```





```{r}

#make a html legend

legend_html <- HTML("
<div style='background:white;
            padding:10px;
            border:1px solid #999;
            border-radius:5px;
            font-size:11px;
            display:inline-block;'>

<table style='border-collapse:collapse;'>

<tr>
<td rowspan='4'
    style='writing-mode:vertical-rl;
           transform:rotate(180deg);
           font-weight:bold;
           padding-right:8px;
           text-align:center;'>
Median annual<br>samples
</td>

<td style='padding-right:5px; text-align:right;'>&ge;5</td>
<td style='background:#be64ac; width:20px; height:20px;'></td>
<td style='background:#8c62aa; width:20px; height:20px;'></td>
<td style='background:#3b4994; width:20px; height:20px;'></td>
</tr>

<tr>
<td style='padding-right:5px; text-align:right;'>2–4</td>
<td style='background:#dfb0d6; width:20px; height:20px;'></td>
<td style='background:#a5add3; width:20px; height:20px;'></td>
<td style='background:#5698b9; width:20px; height:20px;'></td>
</tr>

<tr>
<td style='padding-right:5px; text-align:right;'>1</td>
<td style='background:#e8e8e8; width:20px; height:20px;'></td>
<td style='background:#ace4e4; width:20px; height:20px;'></td>
<td style='background:#5ac8c8; width:20px; height:20px;'></td>
</tr>

<tr>
<td></td>
<td style='text-align:center;'>1</td>
<td style='text-align:center;'>2–3</td>
<td style='text-align:center;'>&ge;4</td>
</tr>

<tr>
<td></td>
<td></td>
<td colspan='3'
    style='text-align:center;
           font-weight:bold;
           padding-top:4px;'>
Years sampled
</td>
</tr>

</table>

</div>
")
```


```{r}
leaflet(site_summaries) |>
  addProviderTiles(providers$CartoDB.Positron) |>
  addCircleMarkers(
    radius = 5,
    stroke = TRUE,
    color = "black",
    weight = 1,
    fill = TRUE,
    fillColor = ~pal(bi_class),
    fillOpacity = 0.9
  ) |>
  addControl(
    legend_html,
    position = "bottomright"
  )
```

